### PR TITLE
 implement real color stack of matching entries

### PR DESCRIPTION
**Pull request by lyokha**
As an example please refer to my last comment on PR #26 (with an image). There I used command

```sh
cgrep -r --color -i contain
```

(wrapped in a script, but this is not important). If pipe output of this in ``less`` you'll see

```
ESC[1mESC[94m./READMEESC[m:21:with older versions of Geant4. Cexmc ESC[1mcESC[mESC[1moESC[mESC[1mnESC[mESC[1mtESC[mESC[1maESC[mESC[1miESC[mESC[1mnESC[ms several optional modules which can
ESC[1mESC[94m./src/CexmcSetup.ccESC[m:291:                 * a logical volume may ESC[1mcESC[mESC[1moESC[mESC[1mnESC[mESC[1mtESC[mESC[1maESC[mESC[1miESC[mESC[1mnESC[m only one sensitive detector. */
ESC[1mESC[94m./src/CexmcSetup.ccESC[m:434:                if ( ( *k )->GetName().ESC[1mcESC[mESC[1moESC[mESC[1mnESC[mESC[1mtESC[mESC[1maESC[mESC[1miESC[mESC[1mnESC[ms( "Right" ) )
ESC[1mESC[94m./src/CexmcSetup.ccESC[m:440:                if ( ( *k )->GetName().ESC[1mcESC[mESC[1moESC[mESC[1mnESC[mESC[1mtESC[mESC[1maESC[mESC[1miESC[mESC[1mnESC[ms( "Right" ) )
ESC[1mESC[94m./src/CexmcHistoManager.ccESC[m:423:        if ( obj->IsFolder() && ( name.ESC[1mCESC[mESC[1moESC[mESC[1mnESC[mESC[1mtESC[mESC[1maESC[mESC[1miESC[mESC[1mnESC[ms( TString( "_arreal_" ) ) ||
ESC[1mESC[94m./src/CexmcHistoManager.ccESC[m:424:                                  name.ESC[1mCESC[mESC[1moESC[mESC[1mnESC[mESC[1mtESC[mESC[1maESC[mESC[1miESC[mESC[1mnESC[ms( TString( "_arrec_" ) ) ) )
ESC[1mESC[94m./src/CexmcEventAction.ccESC[m:29:#include <G4TrajectoryESC[1mCESC[mESC[1moESC[mESC[1mnESC[mESC[1mtESC[mESC[1maESC[mESC[1miESC[mESC[1mnESC[mer.hh>
ESC[1mESC[94m./src/CexmcEventAction.ccESC[m:547:    G4TrajectoryESC[1mCESC[mESC[1moESC[mESC[1mnESC[mESC[1mtESC[mESC[1maESC[mESC[1miESC[mESC[1mnESC[mer *  trajESC[1mCESC[mESC[1moESC[mESC[1mnESC[mESC[1mtESC[m
ESC[1maESC[mESC[1miESC[mESC[1mnESC[mer( event->GetTrajectoryESC[1mCESC[mESC[1moESC[mESC[1mnESC[mESC[1mtESC[mESC[1maESC[mESC[1miESC[mESC[1mnESC[mer() );
ESC[1mESC[94m./src/CexmcEventAction.ccESC[m:549:    if ( ! trajESC[1mCESC[mESC[1moESC[mESC[1mnESC[mESC[1mtESC[mESC[1maESC[mESC[1miESC[mESC[1mnESC[mer )
ESC[1mESC[94m./src/CexmcEventAction.ccESC[m:552:    nTraj = trajESC[1mCESC[mESC[1moESC[mESC[1mnESC[mESC[1mtESC[mESC[1maESC[mESC[1miESC[mESC[1mnESC[mer->entries();
ESC[1mESC[94m./src/CexmcEventAction.ccESC[m:556:        G4VTrajectory *  traj( ( *trajESC[1mCESC[mESC[1moESC[mESC[1mnESC[mESC[1mtESC[mESC[1maESC[mESC[1miESC[mESC[1mnESC[mer )[ i ] );
ESC[1mESC[94m./src/CexmcRunManager.ccESC[m:979:            G4cout << "  -- (fdb file ESC[1mcESC[mESC[1moESC[mESC[1mnESC[mESC[1mtESC[mESC[1maESC[mESC[1miESC[mESC[1mnESC[ms " <<
ESC[1mESC[94m./src/CexmcException.ccESC[m:119:        return CEXMC_LINE_START "Custom filter source file ESC[1mcESC[mESC[1moESC[mESC[1mnESC[mESC[1mtESC[mESC[1maESC[mESC[1miESC[mESC[1mnESC[ms errors. "
```

i.e. every character in a match forms a separate stack of colour escape sequences with ``ESC``, but this is not convenient. In this PR matching characters form bigger colour stacks like this:

```
ESC[1mESC[94m./READMEESC[m:21:with older versions of Geant4. Cexmc ESC[1mcontainESC[ms several optional modules which can
ESC[1mESC[94m./src/CexmcSetup.ccESC[m:291:                 * a logical volume may ESC[1mcontainESC[m only one sensitive detector. */
ESC[1mESC[94m./src/CexmcSetup.ccESC[m:434:                if ( ( *k )->GetName().ESC[1mcontainESC[ms( "Right" ) )
ESC[1mESC[94m./src/CexmcSetup.ccESC[m:440:                if ( ( *k )->GetName().ESC[1mcontainESC[ms( "Right" ) )
ESC[1mESC[94m./src/CexmcHistoManager.ccESC[m:423:        if ( obj->IsFolder() && ( name.ESC[1mContainESC[ms( TString( "_arreal_" ) ) ||
ESC[1mESC[94m./src/CexmcHistoManager.ccESC[m:424:                                  name.ESC[1mContainESC[ms( TString( "_arrec_" ) ) ) )
ESC[1mESC[94m./src/CexmcEventAction.ccESC[m:29:#include <G4TrajectoryESC[1mContainESC[mer.hh>
ESC[1mESC[94m./src/CexmcEventAction.ccESC[m:547:    G4TrajectoryESC[1mContainESC[mer *  trajESC[1mContainESC[mer( event->GetTrajectoryESC[1mContainESC[mer() );
ESC[1mESC[94m./src/CexmcEventAction.ccESC[m:549:    if ( ! trajESC[1mContainESC[mer )
ESC[1mESC[94m./src/CexmcEventAction.ccESC[m:552:    nTraj = trajESC[1mContainESC[mer->entries();
ESC[1mESC[94m./src/CexmcEventAction.ccESC[m:556:        G4VTrajectory *  traj( ( *trajESC[1mContainESC[mer )[ i ] );
ESC[1mESC[94m./src/CexmcRunManager.ccESC[m:979:            G4cout << "  -- (fdb file ESC[1mcontainESC[ms " <<
ESC[1mESC[94m./src/CexmcException.ccESC[m:119:        return CEXMC_LINE_START "Custom filter source file ESC[1mcontainESC[ms errors. "
```

I tested this for multiple matches in one line and it works fine. I also checked that overall performance did not regress.

The patch is mostly useful in scripts like ``cgr`` from the mentioned comment which replace colour escape sequences: it makes them work less and so increase overall performance (in case of ``cgr`` I found that performance got better up to 20-30%).

### CODE REVIEW

**Comment by awgn** [comment]
Cool Alexey! Thanks!

**Comment by awgn** [comment]
Alexey, let me know when you are done with these improvements so that we can release it officially on hackage.  :+1:

**Comment by lyokha** [comment]
Hi Nicola.  I think it's done.

**Comment by awgn** [comment]
Ok, tomorrow I make a new release. Thanks!

On Sat, Oct 31, 2015 at 9:29 AM, Alexey Radkov <notifications@github.com>
wrote:

> Hi Nicola. I think it's done.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/awgn/cgrep/pull/27#issuecomment-152715077>.
>



-- 
The difference between theory and practice is bigger in practice than in
theory.

**Pull request merged**
